export const wordBank: Record<string, string[]> = {
  en: [
    'Apple', 'Guitar', 'Sunshine', 'Ocean', 'Mountain', 'Bicycle', 'Telescope', 'Adventure', 'Coffee', 'Dream',
    'Library', 'Dragon', 'Symphony', 'Butterfly', 'Chocolate', 'Volcano', 'Galaxy', 'Whale', 'Robot', 'Pyramid',
    'Jungle', 'Carnival', 'Mirror', 'Key', 'Bridge', 'Shadow', 'Whisper', 'Rainbow', 'Clock', 'Storm', 'Feather',
    'River', 'Magic', 'Compass', 'Secret', 'Treasure', 'Moonlight', 'Silence', 'Echo', 'Puzzle', 'Desert',
    'Waterfall', 'Island', 'Castle', 'Forest', 'Ship', 'Train', 'Car', 'Airplane', 'Submarine', 'Helicopter',
    'Balloon', 'Rocket', 'Kite', 'Map', 'Book', 'Pen', 'Pencil', 'Paper', 'Computer', 'Phone', 'Television',
    'Radio', 'Camera', 'Photograph', 'Painting', 'Sculpture', 'Poem', 'Song', 'Dance', 'Movie', 'Theater', 'Game',
    'Sport', 'Ball', 'Team', 'Player', 'Friend', 'Family', 'Love', 'Hate', 'Happy', 'Sad', 'Angry', 'Fear', 'Surprise',
    'Joy', 'Peace', 'War', 'Life', 'Death', 'Time', 'Space', 'Energy', 'Matter', 'Light', 'Dark', 'Hot', 'Cold',
    'Up', 'Down', 'Left', 'Right', 'Big', 'Small', 'Fast', 'Slow', 'Old', 'New', 'Good', 'Bad', 'Easy', 'Hard', 'Rich',
    'Poor', 'Strong', 'Weak', 'Brave', 'Coward', 'Wise', 'Foolish', 'Funny', 'Serious', 'Kind', 'Cruel', 'Polite',
    'Rude', 'Honest', 'Dishonest', 'Loyal', 'Disloyal', 'Patient', 'Impatient', 'Generous', 'Stingy', 'Humble',
    'Arrogant', 'Modest', 'Vain', 'Curious', 'Indifferent', 'Creative', 'Dull', 'Optimistic', 'Pessimistic',
    'Positive', 'Negative', 'Success', 'Failure', 'Victory', 'Defeat', 'Health', 'Sickness', 'Wealth', 'Poverty',
    'Knowledge', 'Ignorance', 'Wisdom', 'Folly', 'Beauty', 'Ugliness', 'Truth', 'Lie', 'Justice', 'Injustice',
    'Freedom', 'Slavery', 'Hope', 'Despair', 'Faith', 'Doubt', 'Courage', 'Confidence', 'Insecurity',
    'Happiness', 'Sadness', 'Excitement', 'Boredom', 'Calm', 'Anxiety', 'Relaxation', 'Stress', 'Satisfaction',
    'Disappointment', 'Gratitude', 'Ingratitude', 'Empathy', 'Apathy', 'Sympathy', 'Antipathy', 'Passion',
    'Ambition', 'Laziness', 'Motivation', 'Discipline', 'Chaos', 'Order', 'Disorder', 'Simplicity',
    'Complexity', 'Clarity', 'Confusion', 'Certainty', 'Uncertainty', 'Beginning', 'End', 'Start', 'Finish',
    'Birth', 'Childhood', 'Adulthood', 'Past', 'Present', 'Future', 'History', 'Science', 'Art', 'Music',
    'Literature', 'Philosophy', 'Religion', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Geography',
    'Astronomy', 'Psychology', 'Sociology', 'Economics', 'Politics', 'Law', 'Medicine', 'Engineering',
    'Technology', 'Nature', 'Animal', 'Plant', 'Human', 'Food', 'Drink', 'House', 'Home', 'School', 'Work'
  ],
  es: [
    'Manzana', 'Guitarra', 'Sol', 'Océano', 'Montaña', 'Bicicleta', 'Telescopio', 'Aventura', 'Café', 'Sueño',
    'Biblioteca', 'Dragón', 'Sinfonía', 'Mariposa', 'Chocolate', 'Volcán', 'Galaxia', 'Ballena', 'Robot', 'Pirámide',
    'Selva', 'Carnaval', 'Espejo', 'Llave', 'Puente', 'Sombra', 'Susurro', 'Arcoíris', 'Reloj', 'Tormenta',
    'Pluma', 'Río', 'Magia', 'Brújula', 'Secreto', 'Tesoro', 'Luz de luna', 'Silencio', 'Eco', 'Rompecabezas',
    'Desierto', 'Cascada', 'Isla', 'Castillo', 'Bosque', 'Barco', 'Tren', 'Coche', 'Avión', 'Submarino',
    'Helicóptero', 'Globo', 'Cohete', 'Cometa', 'Mapa', 'Libro', 'Bolígrafo', 'Lápiz', 'Papel', 'Ordenador',
    'Teléfono', 'Televisión', 'Radio', 'Cámara', 'Fotografía', 'Pintura', 'Escultura', 'Poema', 'Canción',
    'Baile', 'Película', 'Teatro', 'Juego', 'Deporte', 'Balón', 'Equipo', 'Jugador', 'Amigo', 'Familia',
    'Amor', 'Odio', 'Feliz', 'Triste', 'Enfadado', 'Miedo', 'Sorpresa', 'Alegría', 'Paz', 'Guerra', 'Vida',
    'Muerte', 'Tiempo', 'Espacio', 'Energía', 'Materia', 'Luz', 'Oscuridad', 'Caliente', 'Frío', 'Arriba',
    'Abajo', 'Izquierda', 'Derecha', 'Grande', 'Pequeño', 'Rápido', 'Lento', 'Viejo', 'Nuevo', 'Bueno', 'Malo',
    'Fácil', 'Difícil', 'Rico', 'Pobre', 'Fuerte', 'Débil', 'Valiente', 'Cobarde', 'Sabio', 'Tonto', 'Divertido',
    'Serio', 'Amable', 'Cruel', 'Educado', 'Grocero', 'Honesto', 'Deshonesto', 'Leal', 'Desleal', 'Paciente',
    'Impaciente', 'Generoso', 'Tacaño', 'Humilde', 'Arrogante', 'Modesto', 'Vanidoso', 'Curioso',
    'Indiferente', 'Creativo', 'Aburrido', 'Optimista', 'Pesimista', 'Positivo', 'Negativo', 'Éxito',
    'Fracaso', 'Victoria', 'Derrota', 'Salud', 'Enfermedad', 'Riqueza', 'Pobreza', 'Conocimiento',
    'Ignorancia', 'Sabiduría', 'Tontería', 'Belleza', 'Fealdad', 'Verdad', 'Mentira', 'Justicia',
    'Injusticia', 'Libertad', 'Esclavitud', 'Esperanza', 'Desesperación', 'Fe', 'Duda', 'Coraje', 'Confianza',
    'Inseguridad', 'Felicidad', 'Tristeza', 'Emoción', 'Aburrimiento', 'Calma', 'Ansiedad', 'Relajación',
    'Estrés', 'Satisfacción', 'Decepción', 'Gratitud', 'Ingratitud', 'Empatía', 'Apatía', 'Simpatía',

    'Antipatía', 'Pasión', 'Ambición', 'Pereza', 'Motivación', 'Disciplina', 'Caos', 'Orden',
    'Desorden', 'Sencillez', 'Complejidad', 'Claridad', 'Confusión', 'Certeza', 'Incertidumbre',
    'Principio', 'Fin', 'Comienzo', 'Nacimiento', 'Infancia', 'Adultez', 'Pasado', 'Presente',
    'Futuro', 'Historia', 'Ciencia', 'Arte', 'Música', 'Literatura', 'Filosofía', 'Religión',
    'Matemáticas', 'Física', 'Química', 'Biología', 'Geografía', 'Astronomía', 'Psicología', 'Sociología',
    'Economía', 'Política', 'Ley', 'Medicina', 'Ingeniería', 'Tecnología', 'Naturaleza', 'Animal', 'Planta',
    'Humano', 'Comida', 'Bebida', 'Casa', 'Hogar', 'Escuela', 'Trabajo'
  ],
  ar: [
    'تفاحة', 'جيتار', 'شمس', 'محيط', 'جبل', 'دراجة', 'تلسكوب', 'مغامرة', 'قهوة', 'حلم',
    'مكتبة', 'تنين', 'سيمفونية', 'فراشة', 'شوكولاتة', 'بركان', 'مجرة', 'حوت', 'روبوت', 'هرم',
    'غابة', 'كرنفال', 'مرآة', 'مفتاح', 'جسر', 'ظل', 'همس', 'قوس قزح', 'ساعة', 'عاصفة',
    'ريشة', 'نهر', 'سحر', 'بوصلة', 'سر', 'كنز', 'ضوء القمر', 'صمت', 'صدى', 'لغز',
    'صحراء', 'شلال', 'جزيرة', 'قلعة', 'سفينة', 'قطار', 'سيارة', 'طائرة', 'غواصة', 'هليكوبتر',
    'بالون', 'صاروخ', 'طائرة ورقية', 'خريطة', 'كتاب', 'قلم', 'قلم رصاص', 'ورق', 'كمبيوتر', 'هاتف',
    'تلفزيون', 'راديو', 'كاميرا', 'صورة', 'لوحة', 'نحت', 'قصيدة', 'أغنية', 'رقص', 'فيلم',
    'مسرح', 'لعبة', 'رياضة', 'كرة', 'فريق', 'لاعب', 'صديق', 'عائلة', 'حب', 'كره',
    'سعيد', 'حزين', 'غاضب', 'خوف', 'مفاجأة', 'فرح', 'سلام', 'حرب', 'حياة', 'موت',
    'وقت', 'فضاء', 'طاقة', 'مادة', 'ضوء', 'ظلام', 'حار', 'بارد', 'فوق', 'تحت',
    'يسار', 'يمين', 'كبير', 'صغير', 'سريع', 'بطيء', 'قديم', 'جديد', 'جيد', 'سيء',
    'سهل', 'صعب', 'غني', 'فقير', 'قوي', 'ضعيف', 'شجاع', 'جبان', 'حكيم', 'أحمق',
    'مضحك', 'جاد', 'لطيف', 'قاس', 'مهذب', 'وقح', 'صادق', 'كاذب', 'مخلص', 'خوان',
    'صبور', 'نافذ الصبر', 'كريم', 'بخيل', 'متواضع', 'متكبر', 'متواضع', 'مغرور', 'فضولي',
    'غير مبال', 'مبدع', 'ممل', 'متفائل', 'متشائم', 'إيجابي', 'سلبي', 'نجاح', 'فشل',
    'نصر', 'هزيمة', 'صحة', 'مرض', 'ثروة', 'فقر', 'معرفة', 'جهل', 'حكمة', 'حماقة',
    'جمال', 'قبح', 'حقيقة', 'كذب', 'عدالة', 'ظلم', 'حرية', 'عبودية', 'أمل', 'يأس',
    'إيمان', 'شك', 'شجاعة', 'ثقة', 'انعدام الأمن', 'سعادة', 'حزن', 'إثارة', 'ملل',
    'هدوء', 'قلق', 'استرخاء', 'ضغط', 'رضا', 'خيبة أمل', 'امتنان', 'جحود', 'تعاطف',
    'لامبالاة', 'شفقة', 'كراهية', 'شغف', 'طموح', 'كسل', 'دافع', 'انضباط',
    'فوضى', 'نظام', 'اضطراب', 'بساطة', 'تعقيد', 'وضوح', 'ارتباك', 'يقين', 'شك',
    'بداية', 'نهاية', 'انطلاق', 'ولادة', 'طفولة', 'بلوغ', 'ماض', 'حاضر', 'مستقبل',
    'تاريخ', 'علم', 'فن', 'موسيقى', 'أدب', 'فلسفة', 'دين', 'رياضيات', 'فيزياء',
    'كيمياء', 'أحياء', 'جغرافيا', 'فلك', 'علم نفس', 'علم اجتماع', 'اقتصاد', 'سياسة',
    'قانون', 'طب', 'هندسة', 'تكنولوجيا', 'طبيعة', 'حيوان', 'نبات', 'إنسان', 'طعام',
    'شراب', 'منزل', 'بيت', 'مدرسة', 'عمل'
  ],
  he: [
    'תפוח', 'גיטרה', 'שמש', 'אוקיינוס', 'הר', 'אופניים', 'טלסקופ', 'הרפתקה', 'קפה', 'חלום',
    'ספרייה', 'דרקון', 'סימפוניה', 'פרפר', 'שוקולד', 'הר געש', 'גלקסיה', 'לוויתן', 'רובוט', 'פירמידה',
    'ג׳ונגל', 'קרנבל', 'מראה', 'מפתח', 'גשר', 'צל', 'לחישה', 'קשת', 'שעון', 'סערה',
    'נוצה', 'נהר', 'קסם', 'מצפן', 'סוד', 'אוצר', 'אור ירח', 'שקט', 'הד', 'פאזל',
    'מדבר', 'מפל', 'אי', 'טירה', 'יער', 'ספינה', 'רכבת', 'מכונית', 'מטוס', 'צוללת',
    'מסוק', 'בלון', 'טיל', 'עפיפון', 'מפה', 'ספר', 'עט', 'עיפרון', 'נייר', 'מחשב',
    'טלפון', 'טלוויזיה', 'רדיו', 'מצלמה', 'צילום', 'ציור', 'פסל', 'שיר', 'ריקוד', 'סרט',
    'תיאטרון', 'משחק', 'ספורט', 'כדור', 'קבוצה', 'שחקן', 'חבר', 'משפחה', 'אהבה', 'שנאה',
    'שמח', 'עצוב', 'כועס', 'פחד', 'הפתעה', 'שמחה', 'שלום', 'מלחמה', 'חיים', 'מוות',
    'זמן', 'חלל', 'אנרגיה', 'חומר', 'אור', 'חושך', 'חם', 'קר', 'למעלה', 'למטה',
    'שמאל', 'ימין', 'גדול', 'קטן', 'מהיר', 'איטי', 'ישן', 'חדש', 'טוב', 'רע',
    'קל', 'קשה', 'עשיר', 'עני', 'חזק', 'חלש', 'אמיץ', 'פחדן', 'חכם', 'טיפש',
    'מצחיק', 'רציני', 'אדיב', 'אכזרי', 'מנומס', 'גס רוח', 'כן', 'שקרן', 'נאמן', 'בוגד',
    'סבלני', 'חסר סבלנות', 'נדיב', 'קמצן', 'צנוע', 'יהיר', 'ביישן', 'שחצן', 'סקרן',
    'אדיש', 'יצירתי', 'משעמם', 'אופטימי', 'פסימי', 'חיובי', 'שלילי', 'הצלחה', 'כישלון',
    'ניצחון', 'תבוסה', 'בריאות', 'מחלה', 'עושר', 'עוני', 'ידע', 'בורות', 'חוכמה', 'שטות',
    'יופי', 'כיעור', 'אמת', 'שקר', 'צדק', 'אי צדק', 'חופש', 'עבדות', 'תקווה', 'ייאוש',
    'אמונה', 'ספק', 'אומץ', 'ביטחון', 'חוסר ביטחון', 'אושר', 'עצב', 'התרגשות', 'שעמום',
    'רוגע', 'חרדה', 'רגיעה', 'לחץ', 'סיפוק', 'אכזבה', 'הכרת תודה', 'כפיות טובה', 'אמפתיה',
    'אדישות', 'סימפתיה', 'אנטיפתיה', 'תשוקה', 'שאפתנות', 'עצלות', 'מוטיבציה', 'משמעת',
    'כאוס', 'סדר', 'אי סדר', 'פשטות', 'מורכבות', 'בהירות', 'בלבול', 'ודאות', 'אי ודאות',
    'התחלה', 'סוף', 'לידה', 'ילדות', 'בגרות', 'עבר', 'הווה', 'עתיד',
    'היסטוריה', 'מדע', 'אמנות', 'מוזיקה', 'ספרות', 'פילוסופיה', 'דת', 'מתמטיקה', 'פיזיקה',
    'כימיה', 'ביולוגיה', 'גאוגרפיה', 'אסטרונומיה', 'פסיכולוגיה', 'סוציולוגיה', 'כלכלה',
    'פוליטיקה', 'חוק', 'רפואה', 'הנדסה', 'טכנולוגיה', 'טבע', 'חיה', 'צמח', 'אדם', 'אוכל',
    'שתייה', 'בית', 'מدرسة', 'עבודה'
  ]
};
